name: docker-image

on:
  push:
    branches:
      - main

jobs:
  images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build:
          - type: raw
          - type: bash
          - type: bash-exec
          - type: bash-dumb-init
    steps:
      - name: Get current date
        run: echo "curr_date=$(date --utc +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push main
        id: docker_build_main
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.build.type }}.Dockerfile
          pull: true
          push: true
          tags: ghcr.io/bakito/sigterm:1.0.0-${{ matrix.build.type }}
          platforms: linux/amd64
          provenance: false

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
